##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /
#
# frozen_string_literal: true

module Textgrid
  module REST
    class Insights < Domain
      ##
      # Initialize the Insights Domain
      def initialize(twilio)
        super

        @base_url = 'https://insights.twilio.com'
        @host = 'insights.twilio.com'
        @port = 443

        # Versions
        @v1 = nil
      end

      ##
      # Version v1 of insights
      def v1
        @v1 ||= V1.new self
      end

      ##
      # @return [Textgrid::REST::Insights::V1::SettingInstance]
      def settings
        self.v1.settings()
      end

      ##
      # @param [String] call_sid The call_sid
      # @return [Textgrid::REST::Insights::V1::AnnotationInstance] if call_sid was passed.
      # @return [Textgrid::REST::Insights::V1::AnnotationList]
      def annotation(call_sid=:unset)
        self.v1.annotation(call_sid)
      end

      ##
      # @param [String] sid The sid
      # @return [Textgrid::REST::Insights::V1::CallInstance] if sid was passed.
      # @return [Textgrid::REST::Insights::V1::CallList]
      def calls(sid=:unset)
        self.v1.calls(sid)
      end

      ##
      # @return [Textgrid::REST::Insights::V1::CallSummariesInstance]
      def call_summaries
        self.v1.call_summaries()
      end

      ##
      # @param [String] conference_sid The unique SID identifier of the Conference.
      # @return [Textgrid::REST::Insights::V1::ConferenceInstance] if conference_sid was passed.
      # @return [Textgrid::REST::Insights::V1::ConferenceList]
      def conferences(conference_sid=:unset)
        self.v1.conferences(conference_sid)
      end

      ##
      # @param [String] room_sid Unique identifier for the room.
      # @return [Textgrid::REST::Insights::V1::RoomInstance] if room_sid was passed.
      # @return [Textgrid::REST::Insights::V1::RoomList]
      def rooms(room_sid=:unset)
        self.v1.rooms(room_sid)
      end

      ##
      # Provide a user friendly representation
      def to_s
        '#<Textgrid::REST::Insights>'
      end
    end
  end
end
