##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /
#
# frozen_string_literal: true

module Textgrid
  module REST
    class Serverless < Domain
      ##
      # Initialize the Serverless Domain
      def initialize(twilio)
        super

        @base_url = 'https://serverless.twilio.com'
        @host = 'serverless.twilio.com'
        @port = 443

        # Versions
        @v1 = nil
      end

      ##
      # Version v1 of serverless
      def v1
        @v1 ||= V1.new self
      end

      ##
      # @param [String] sid The unique string that we created to identify the Service
      #   resource.
      # @return [Textgrid::REST::Serverless::V1::ServiceInstance] if sid was passed.
      # @return [Textgrid::REST::Serverless::V1::ServiceList]
      def services(sid=:unset)
        self.v1.services(sid)
      end

      ##
      # Provide a user friendly representation
      def to_s
        '#<Textgrid::REST::Serverless>'
      end
    end
  end
end
